spring:
  datasource:
#    url: jdbc:postgresql://db.mnkhvuueujpudubdnzad.supabase.co:5432/postgres
    url: jdbc:postgresql://localhost:5432/movies
    username: postgres
#    password: yWn1yh2DSqO7s9ZQ
    password: admin


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    security:
      jwt:
        secret-key

server:
  port: 8088

application:
  security:
    jwt:
      secret-key: YTJLOTNsUDB4OVF3TG1ON3ZCY0Q1clR5VWlPMTIzNDU2Nzg5QUJDREVGR0g=
      refresh-token-expiration: 604800000
      expiration: 3600000

  late-fee:
    daily-amount: 2000
